apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-deployment
  labels:
    app: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops
  template:
    metadata:
      labels:
        app: devops 
    spec:
      containers:
      - name: devopsserver
        image: devops:latest
        ports:
        - containerPort: 4200
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: devops-service
spec:
  selector:
    app: devops 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 4200
    nodePort: 31110
