---
  tasks:
    - name: copy Dockerfile
      copy:
        src: ./dockerfile
        dest: /root/
        owner: root
        group: root
        mode: '0644'
    - name: build container image
      docker_image:
        name: devops
        build:
          path: /var/lib/jenkins/workspace/LivraisonContinue
          source: build
        state: present
