---
# tasks file for docker
- name: create image docker
  docker_image:
    build:
      name: devops
      path: /var/lib/jenkins/workspace/Second_Pipeline
      pull: no
      state: present
      force: true
- name: run container docker
  docker_container:
    name: myapp_container
    image: devops:latest
    state: started
    recreate: true
    ports:
    
      - "4200:80"
