---
# tasks file for docker
- name: create image docker
  docker_image:
    name: devops
    build:
    path: /var/lib/jenkins/workspace/Second_Pipeline
    
    source: build
    state: present
    
- name: run container docker
  docker_container:
    name: myapp_container
    image: devops:latest
    state: started
    
    ports:
    
      - "4200:80"   
