---
    - name: build container image
      docker_image:
        name: devops
        build:
          path: /var/lib/jenkins/workspace/LivraisonContinue
         source: build
         state: present
         force_source: true
         pull: no
   - name: run container docker
     docker_container:
     name: myapp_container
     image: devops:latest
     state: started
     recreate: true
     ports:
    
      - "4200:80"
