---
    - name: build container image
      docker_image:
        name: devops
        build:
          path: /var/lib/jenkins/workspace/LivraisonContinue
          source: build
        state: present
